version: '3.8'

services:
  pg_job:
    image: postgres:15
    container_name: job_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - job_pgdata:/var/lib/postgresql/data
    networks:
      - job_net

volumes:
  job_pgdata:

networks:
  job_net:
    driver: bridge